### ISSUE TITLE
Mustard TV

### ISSUE THREAD

**Issue by unlocKing** [SilentButeo2/webgrabplus-siteinipack#123]
Can't find any data for Mustard TV Norwich anywhere except:

http://www.mustardtv.co.uk/schedule/

Can someone help with this?

Thanks.

**Comment by SilentButeo2** [comment]
What about these link:
siteini.pack/Denmark/dk.timefor.tv.channels.xml
siteini.pack/Sweden/se.timefor.tv.channels.xml

Both have "mustard-tv"

**Comment by unlocKing** [comment]
Mustard TV is a new local UK channel.
