### ISSUE TITLE
Sheffield Live TV

### ISSUE THREAD

**Issue by unlocKing** [SilentButeo2/webgrabplus-siteinipack#124]
Can't find any data for Sheffield Live TV anywhere except:

http://web.sheffieldlive.org/show/tv-schedule/

Can someone help with this?

Thanks.

**Comment by SilentButeo2** [comment]
What about these link:
siteini.pack/Denmark/dk.timefor.tv.channels.xml
siteini.pack/Sweden/se.timefor.tv.channels.xml

Both have "sheffield-live"

**Comment by unlocKing** [comment]
Sheffield Live is a new local UK channel.
