### ISSUE TITLE
Bay TV

### ISSUE THREAD

**Issue by unlocKing** [SilentButeo2/webgrabplus-siteinipack#169]
Can't find any data for Bay TV anywhere except:

http://www.baytvswansea.com/schedule

Can someone help with this?

Thanks.

**Comment by SilentButeo2** [comment]
<channel update="i" site="se.timefor.tv" site_id="bay-tv" xmltv_id="UK Bay TV Liverpool">UK Bay TV Liverpool</channel>
?

**Comment by unlocKing** [comment]
Bay TV is a new channel in Wales.
