### ISSUE TITLE
Switzerland horizon.tv.ch not working anymore

### ISSUE THREAD

**Issue by lpillonel** [SilentButeo2/webgrabplus-siteinipack#18]
Has anybody an idea ?

Here is the log :

````
[  Info  ] (   9/53  ) HORIZON.TV.CH -- chan. (xmltv_id=ITV HD) -- mode Incremental
[Warning ] error downloading page: Error: SendFailure (Error writing headers)
[Warning ] pausing 1 of 4 times for 30 seconds before re-try.
[Warning ] error downloading page: Error: SendFailure (Error writing headers)
[Warning ] pausing 2 of 4 times for 60 seconds before re-try.
[Warning ] error downloading page: The request timed out (90sec)
[Warning ] Retry 3 of 4 times
[Warning ] error downloading page: The request timed out (120sec)
[Warning ] Retry 4 of 4 times
[        ] Job finished at 19/01/2017 03:05:43 done in 5m 8s
[Critical] Unhandled Exception
[Critical] 
Index was outside the bounds of the array.
[Critical] 
  at WGconsole.Program.ConsoleApplication (System.String[] args) <0x416bb000 + 0x06c4f> in <filename unknown>:0 
  at WGconsole.Program.Main (System.String[] args) <0x416b2e20 + 0x000a7> in <filename unknown>:0 
[Critical] For detailed info, see log file WebGrab++.log.txt
[Critical] Execution stopped
````

Thanks

**Comment by WGMaker** [comment]
Hi Luca,

I see nothing wrong when I try. Does the error persist?

Jan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lpillonel** [comment]
Yep still the same issue...
I have as `horizon.tv.channel` : 

    <channel update="i" site="horizon.tv.ch" site_id="256616999390" xmltv_id="M6 HD">M6 HD</channel>
    <channel update="i" site="horizon.tv.ch" site_id="27909159180" xmltv_id="Channel 5">Channel 5</channel>
    <channel update="i" site="horizon.tv.ch" site_id="27909159193" xmltv_id="France 24">France 24</channel>
    <channel update="i" site="horizon.tv.ch" site_id="27909159217" xmltv_id="TV5MONDE">TV5MONDE</channel>

**Comment by freddysmith1** [comment]
ive just started getting the same aswell . on linux system, will try a whole new config again

**Comment by WGMaker** [comment]
Strange if I run it no problems!

Group (0) :
[  Info  ] update requested for - 4 - out of - 4 - channels for 1 day(s)
[  Debug ] 
[  Info  ] (   1/4   ) HORIZON.TV.CH -- chan. (xmltv_id=M6 HD) -- mode Force
[  Debug ]    skipped : show that happened before 'today' @ 25/01/2017 23:15
[  Info  ] 
[  Debug ] 
[  Info  ] (   2/4   ) HORIZON.TV.CH -- chan. (xmltv_id=Channel 5) -- mode Force
[  Debug ]    skipped : show that happened before 'today' @ 25/01/2017 23:05
[  Info  ] 
[  Debug ] 
[  Info  ] (   3/4   ) HORIZON.TV.CH -- chan. (xmltv_id=France 24) -- mode Force
[  Debug ]    skipped : show that happened before 'today' @ 25/01/2017 23:00
[  Debug ]    skipped : show that happened before 'today' @ 25/01/2017 23:11
[  Debug ]    skipped : show that happened before 'today' @ 25/01/2017 23:30
[  Debug ]    skipped : show that happened before 'today' @ 25/01/2017 23:32
[  Debug ]    skipped : show that happened before 'today' @ 25/01/2017 23:58
[  Info  ] 
[  Debug ] 
[  Info  ] (   4/4   ) HORIZON.TV.CH -- chan. (xmltv_id=TV5MONDE) -- mode Force
[  Info  ] 
[  Debug ] 
[  Debug ] 317 shows in 4 channels
[  Debug ] 0 updated shows
[  Debug ] 317 new shows added

This is the guide:
[guide.zip](https://github.com/SilentButeo2/webgrabplus-siteinipack/files/732495/guide.zip)

What WG++ version are you using?

**Comment by lpillonel** [comment]
Maybe my IP get banned or something like that ?

**Comment by unlocKing** [comment]
Site may have changed, have you tried creating a cookie?

**Comment by WGMaker** [comment]
Just to ask again: Which WG++ version are you using?

**Comment by lpillonel** [comment]
I have version V1.57 running on libreelec x86.

Still not working btw

**Comment by Netuddki** [comment]
There is a new horizon.tv ini in the international directory. Old horizon country inis don't work anymore.
