### ISSUE TITLE
RaiItalia.it.ini is a duplicate of rai.it.ini

### ISSUE THREAD

**Issue by Pancronos** [SilentButeo2/webgrabplus-siteinipack#200]
url_index is the same

**Comment by Netuddki** [comment]
No it is not!
RaiItalia3 is the international version of RaiItalia, which is not listed in the rai.it.ini

Rai Tre (or Rai 3) is not the same as RaiItalia3!

**Comment by Netuddki** [comment]
http://www.raiplay.it/guidatv/
Is the italian Rai Guide

http://www.raitalia.it/dl/portali/site/custom/guidaprogrammi_raiItalia.html
Is the International Rai Italia guide which is not broadcasted in Italy, but only in foreign countries over Satelite

**Comment by Pancronos** [comment]
http://www.raitalia.it/dl/portale/html/palinsesti/guidatv/static/RaiItalia1_2017_05_29.html
http://www.raitalia.it/dl/portale/html/palinsesti/guidatv/static/RaiItalia2Australia_2017_05_29.html
http://www.raitalia.it/dl/portale/html/palinsesti/guidatv/static/RaiItalia2Asia_2017_05_29.html
http://www.raitalia.it/dl/portale/html/palinsesti/guidatv/static/RaiItalia3_2017_05_29.html

these are the correct links then and you should have 4 channel in your channel.xml if you want the international channels. Anyway as the old ini works and since url_index is the same you can use that one. Just need to add example: <channel update="i" site="rai.it" site_id="RaiItalia2Asia" xmltv_id="Rai Italia 2 Asia">Rai Italia 2 Asia</channel>
as Jan's ini is missing channel creation.
RaiPlay is just the new fancy look of RAI.
Bye

**Comment by Pancronos** [comment]
forgot to quote `	<channel update="i" site="rai.it" site_id="RaiItalia2Asia" xmltv_id="Rai Italia 2 Asia">Rai Italia 2 Asia</channel>
`

**Comment by Netuddki** [comment]
I didn't forgot to add those.

They do not matter, because it's allways the same programming, they just change the times by javascript and they are listed for convenience.

The data doesn't change and all times are grabbed in UTC, so it wouldn't matter anyway.

**Comment by Pancronos** [comment]
ok btw i pushed the fix for your urldate.format {datestring|yyy_MM_dd} that is missing one "y"  and thanks for the notts ini correction.
