### ISSUE TITLE
teleman.pl

### ISSUE THREAD

**Issue by popers** [SilentButeo2/webgrabplus-siteinipack#258]
```
   epg correction :
 CHANGED show corrected,
      show with ---- start = 26/06/2017 11:55:00 stop = 26/06/2017 12:40:00 title = Plotkara
      Replaces ----- start = 26/06/2017 11:55:00 stop = 26/06/2017 12:40:00 title = Plotkara
```
or
```
(  62/172 ) TELEMAN.PL -- chan. (xmltv_id=Fokus TV PL) -- mode Incremental
iiiii.....................................c
No episode-num matching
episode-num unchanged: odc. 9/13</h2>




    <script>
(function(d, s, id) {
 var js, fjs = d.getElementsByTagName(s)[0];
 if (d.getElementById(id)) return;
 js = d.createElement(s); js.id = id;
 js.src = "http
   epg correction :
 CHANGED show corrected,
      show with ---- start = 26/06/2017 07:05:00 stop = 26/06/2017 08:00:00 title = Determinator
      Replaces ----- start = 26/06/2017 07:05:00 stop = 26/06/2017 08:00:00 title = Determinator
```
Still making corrections as above

**Comment by piotrasd** [comment]
another bug <coutry> catch wrong data on some programs

`  <programme start="20170628103000 +0200" stop="20170628110000 +0200" channel="13 Ulica">
    <title lang="pl">Akta zbrodni: Kamień przeznaczenia (178)</title>
    <title lang="xx">Forensic Files: Pet Rock</title>
    <desc lang="pl">Młoda kobieta przez dwa dni nie pojawia się w pracy. Wkrótce okazuje się, że została zamordowana. Dowody obciążają tych, którzy zaklinają się, że nie mieli nic wspólnego z tą zbrodnią. Serial ukazuje tajniki dochodzeń prowadzonych przez policję. W każdym odcinku widzowie uczestniczą w prawdziwych śledztwach i razem z policyjnymi ekspertami odkrywają kolejne fakty dotyczące brutalnych przestępstw. W programie pojawiają się miejsca, w których doszło do tych przerażających aktów przemocy, dowody, które pomogły w rozwiązaniu kryminalnej zagadki, a także relacje naocznych świadków. Zobaczymy, jak wygląda codzienna praca lekarzy, techników kryminalnych, policjantów i prawników, którzy współpracują przy rozwiązywaniu nietypowych spraw kryminalnych(n)</desc>
    <credits>
      <director>Paul Dowling</director>
      <director>Sovanna Mam</director>
    </credits>
    <category lang="pl">Serial Paradokumentalny</category>
    <icon src="http://media.teleman.pl/photos/470x265/Akta-Zbrodni-Blotnisty-Slad.jpg" />
    <country>USA</country>
    <country>wtorek, 27 czerwca</country>
    <country>16:30</country>
    <country>środa, 28 czerwca</country>
    <country>1:30</country>
    <country>środa, 28 czerwca</country>
    <country>10:30</country>
    <episode-num system="onscreen">E178</episode-num>
  </programme>`

**Comment by Netuddki** [comment]
I couldn't recreate with Fokus TV. You must say which channel produces these mistakes, so we can actually check and fix it.

I created a new pull request with some fixes though.
