### ISSUE TITLE
tvtv.de not working anymore

### ISSUE THREAD

**Issue by daeks** [SilentButeo2/webgrabplus-siteinipack#347]
as the title already says, the siteini for tvtv.de (germany) is not working anymore. Could someone have a look on it?

**Comment by Kampfader** [comment]
is the tvtv.de Website online?

**Comment by githuborer** [comment]
Yeah tvtv.de is online. This issue is not fixed for months

**Comment by Kampfader** [comment]
Fixed..
https://github.com/SilentButeo2/webgrabplus-siteinipack/pull/389

**Comment by uragan1987** [comment]
fixed tvtv.de for current day
https://github.com/uragan1987/webgrabplus-siteinipack/blob/master/siteini.pack/Germany/tvtv.de.ini
have fun

**Comment by Pancronos** [comment]
new ini available
