### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by VenimK** [SilentButeo2/webgrabplus-siteinipack#375]
Using tvvlaanderen and canaldigitaal
Getting the EPG works ok, but can 't get images to show up in Tvheadend

Links are in guide.xml
<programme start="20190113053000 +0000" stop="20190113071500 +0000" channel="Film 1 Premiere HD">
    <title lang="nl">Commuter, The</title>
    <desc lang="nl">Amerikaans-Frans misdaaddrama Een zakenman raakt tijdens zijn dagelijkse treinreis betrokken bij een crimineel complot.(n)</desc>
    <icon src="https://livetv.canaldigitaal.nl/mmchan/epgimages/zX0jB3lhk3msbpW1iAIeCw.jpg" />

**Comment by Kampfader** [comment]
fixed
https://github.com/SilentButeo2/webgrabplus-siteinipack/pull/389/commits/a506d3918c80a1a5530f403333e47df65240405d
https://github.com/SilentButeo2/webgrabplus-siteinipack/pull/389/commits/e002c224f1b7dc8edcf907c05fb7c6d65bbab024

**Comment by Kampfader** [comment]
if you like the other pictures (not the Cover)

change this line

"index_showicon.modify {replace|epgimages/|epgimages/208x308/}"
to
"index_showicon.modify {replace|epgimages/|epgimages/260x145/}"
