### ISSUE TITLE
Turkey siteini.pack help me please

### ISSUE THREAD

**Issue by docea37** [SilentButeo2/webgrabplus-siteinipack#394]
can not help no longer work

[hurriyet.com.tr.zip](https://github.com/SilentButeo2/webgrabplus-siteinipack/files/2894939/hurriyet.com.tr.zip)
[uydunetkablotv.com.zip](https://github.com/SilentButeo2/webgrabplus-siteinipack/files/2894940/uydunetkablotv.com.zip)

**Comment by Kampfader** [comment]
test this one pls.


[hurriyet.com.tr.ini.zip](https://github.com/SilentButeo2/webgrabplus-siteinipack/files/2897116/hurriyet.com.tr.ini.zip)

**Comment by docea37** [comment]
Thank you for editing. worked.
there is only one problem.
Turkish characters do not recognize.

(ş-ç-ğ-ı-ü)

sample: eÄŸlence==>eğlence
taÅŸÄ±nÄ±yor==> taşınıyor
gerçekleÅŸtirildiÄŸi==> gerçekleştirildiği

**Comment by WGMaker** [comment]
Try other charsets , now charset=windows-1254

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by docea37** [comment]
hello 
hello can you prepare the necessary files for this site
https://canlitv.com/yayin-akisi/

**Comment by docea37** [comment]
Hello there
can you update the existing dsmart.com.tr.ini file.
current file does not work

new address---- https://www.dsmart.com.tr/yayinakisi

**Comment by WGMaker** [comment]
What is your wg username ?

Regards jan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by docea37** [comment]
> Wg kullanıcı adınız nedir? Saygılarımızla jan Posta ile gönderildi < https://go.microsoft.com/fwlink/?LinkId=550986 > Windows 10 için
> [...](#)
> ________________________________ From: docea37 <notifications@github.com> Sent: Tuesday, September 24, 2019 6:07:38 PM To: SilentButeo2/webgrabplus-siteinipack <webgrabplus-siteinipack@noreply.github.com> Cc: WGMaker <janplusjet@live.co.uk>; Comment <comment@noreply.github.com> Subject: Re: [SilentButeo2/webgrabplus-siteinipack] Turkey siteini.pack help me please (#394) Hello there can you update the existing dsmart.com.tr.ini file. current file does not work new address---- https://www.dsmart.com.tr/yayinakisi<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dsmart.com.tr%2Fyayinakisi&data=02%7C01%7C%7C975637e729fd41c6837208d74111b445%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637049416597417143&sdata=Nh24PdQ4lKbT%2Beb%2Bedr%2FUNE8pF%2BIIAvzGGrvURDYABE%3D&reserved=0> — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSilentButeo2%2Fwebgrabplus-siteinipack%2Fissues%2F394%3Femail_source%3Dnotifications%26email_token%3DACE3F4ILA2FLPEPXYXYHBHTQLJCNVA5CNFSM4GZIBPJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7PC5NQ%23issuecomment-534654646&data=02%7C01%7C%7C975637e729fd41c6837208d74111b445%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637049416597427148&sdata=irIrShX0%2FiXlaen9OuLX2EctLFK9ttFxL3ThO2zeFuU%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACE3F4O2UHDIQ6CFBVFRLULQLJCNVANCNFSM4GZIBPJQ&data=02%7C01%7C%7C975637e729fd41c6837208d74111b445%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637049416597437153&sdata=nf%2FsRRs1379anvwrwWq4oMXq7g6r7Xlg6GJfIiVrDio%3D&reserved=0>.

docea37

**Comment by docea37** [comment]
> What is your wg username ? Regards jan Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
> […](#)
> ________________________________ From: docea37 <notifications@github.com> Sent: Tuesday, September 24, 2019 6:07:38 PM To: SilentButeo2/webgrabplus-siteinipack <webgrabplus-siteinipack@noreply.github.com> Cc: WGMaker <janplusjet@live.co.uk>; Comment <comment@noreply.github.com> Subject: Re: [SilentButeo2/webgrabplus-siteinipack] Turkey siteini.pack help me please (#394) Hello there can you update the existing dsmart.com.tr.ini file. current file does not work new address---- https://www.dsmart.com.tr/yayinakisi<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dsmart.com.tr%2Fyayinakisi&data=02%7C01%7C%7C975637e729fd41c6837208d74111b445%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637049416597417143&sdata=Nh24PdQ4lKbT%2Beb%2Bedr%2FUNE8pF%2BIIAvzGGrvURDYABE%3D&reserved=0> — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSilentButeo2%2Fwebgrabplus-siteinipack%2Fissues%2F394%3Femail_source%3Dnotifications%26email_token%3DACE3F4ILA2FLPEPXYXYHBHTQLJCNVA5CNFSM4GZIBPJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7PC5NQ%23issuecomment-534654646&data=02%7C01%7C%7C975637e729fd41c6837208d74111b445%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637049416597427148&sdata=irIrShX0%2FiXlaen9OuLX2EctLFK9ttFxL3ThO2zeFuU%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACE3F4O2UHDIQ6CFBVFRLULQLJCNVANCNFSM4GZIBPJQ&data=02%7C01%7C%7C975637e729fd41c6837208d74111b445%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637049416597437153&sdata=nf%2FsRRs1379anvwrwWq4oMXq7g6r7Xlg6GJfIiVrDio%3D&reserved=0>.

username= docea37

**Comment by Pancronos** [comment]
Updated dsmart
