### ISSUE TITLE
Delete rtvslo.it.ini (Italy)

### ISSUE THREAD

**Issue by Pancronos** [SilentButeo2/webgrabplus-siteinipack#40]
Site is not Italian but Slovenian  http://www.rtvslo.si/
Also in the Slovenian folder there is a newer  Revision 4 - [26/07/2016] Blackbear199

**Comment by SilentButeo2** [comment]
Should be investigated, if this is really not a .it site.

**Comment by Pancronos** [comment]
url ini is the same besides the .it is not grabbing.
