### ISSUE TITLE
Horizon.tv xmltv_ns support?

### ISSUE THREAD

**Issue by glenndehaan** [SilentButeo2/webgrabplus-siteinipack#438]
Is there support for xmltv_ns when using the horizon.tv provider?
If not can this be implemented. I'm using Plex and this requires xmltv_ns as the episode system.

**Comment by Pancronos** [comment]
have you tried to change it in site line ?

**Comment by glenndehaan** [comment]
Yeah but that doesn't change the episode system itself. Only the system="" line.

**Comment by WGMaker** [comment]
For horizon.tv.ini it does change the episode format and the episode system attribute. ! Maybe you use an outdated SiteIni or wg++ version?

Use wg++ version 2.1.9 and horizontv.ini rev7 and set episodesystem=xmltv_ns

Regards Jan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by WGMaker** [comment]
Maybe not clear ... you must change the episodesystem value in the SiteIni line starting with   site , that’s inmediately below the header section

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Jan van Straaten <janplusjet@LIVE.CO.UK>
Sent: Monday, July 1, 2019 12:52:22 PM
To: SilentButeo2/webgrabplus-siteinipack
Subject: RE: [SilentButeo2/webgrabplus-siteinipack] Horizon.tv xmltv_ns support? (#438)

For horizon.tv.ini it does change the episode format and the episode system attribute. ! Maybe you use an outdated SiteIni or wg++ version?

Use wg++ version 2.1.9 and horizontv.ini rev7 and set episodesystem=xmltv_ns

Regards Jan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
