### ISSUE TITLE
id xmltv not update using siptv

### ISSUE THREAD

**Issue by andykimpe** [SilentButeo2/webgrabplus-siteinipack#439]
the id xmltv that are indicate in the files *.channels.xml

do not match the siptv id

off only the use of it's id allows compatibility with smart tv

thank you to correct the id of all files *.channels.xml

to match those of siptv

complete lists on

http://siptv.eu/codes

or

http://siptv.app/codes

eg

in coutry France

channel

TF1

xmltv_id="TF1.fr"

et no

xmltv_id="TF1"

please update for all country and all files *.channels.xml

**Comment by Pancronos** [comment]
you can probably with an editor add/remove (or a script ) match your needs
