### ISSUE TITLE
transvision.co.id

### ISSUE THREAD

**Issue by null2264** [SilentButeo2/webgrabplus-siteinipack#440]
It's no longer working, been looking around the website but they don't get answer of what happend and how to fix/workaround it...
But i have been researching and it looks like they added CSRF Token to the input to prevent this program to grab epg from the web... I would love to know if it's possible to call the value of csrf or any possible workaround.

**Comment by WGMaker** [comment]
Hi,

We have a revision ready which grabs the token first . Unfortunately this needs the coming beta 2.1.11, which is currently being tested. I hope to be confident that it’s good enough at the end of this week. Sorry     regards    Jan van Straaten

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by null2264** [comment]
Good to know that you're working on it, I cant wait for the update to come out

**Comment by null2264** [comment]
I still unable to grab tv guide from TransVision with the new revision, and the fact that the Ini file is encrypted make it harder for me to troubleshoot the problem. I already updated my WG++ to the newest beta, i tried to download cookie.txt from my browser and copy paste it to hot_cookie.txt but no luck. I hope that this problem could be fixed ASAP....

> [  Info  ] (   1/55  ) TRANSVISION.CO.ID -- chan. (xmltv_id=AFC) -- mode Force
> [Error   ] Unable to update channel AFC
> [Critical] Generic syntax exception:
> [Critical]    message: 
> [Error   ] no index page data received from AFC
> [Error   ] unable to update channel, try again later
> [  Info  ] Existing guide data restored!

**Comment by Pancronos** [comment]
did you upgrade to version 2.1.11 ?

**Comment by Pancronos** [comment]
check now

**Comment by null2264** [comment]
Nice, it's working now thank you for the quick fix
