### ISSUE TITLE
custom channel logo & Thumbnail

### ISSUE THREAD

**Issue by Janasek** [SilentButeo2/webgrabplus-siteinipack#443]
**Thanks for canal plus ini**
https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/siteini.pack/Poland/pl.canalplus.com.E.ini

how can I add <icon src = "

**something like that**

<date>2015</date>
category lang="pl">Serial</category
 category lang="pl">Dokumentalny</category
icon src="https://ocdn.eu/program-tv/new-upload-images/images-e69225a7-3390-4b73-b560-ed40a19549c0"/

**and one more question**
how to change url for custom channel logo

**something like that**

index_urlchannellogo.modify {set(not "")|**MY URL FOR LOGO**'index_urlchannellogo'.png}

**the .ini file is quite different from the ones I saw before and were easy to edit**

**Comment by Pancronos** [comment]
you can't because on that site there is no showicon
for logo you can remove it with sed and add your

**Comment by Janasek** [comment]
I definitely don't know how
does not matter
