### ISSUE TITLE
Problem with transvision.co.id

### ISSUE THREAD

**Issue by null2264** [SilentButeo2/webgrabplus-siteinipack#444]
I don't know if this can be fixed by any chance but i'll just leave this here for you to check out,
The EPG is not lining up correctly with the live TV because of how transvision's tv guide style... If you set the date to nothing (like the wg++ did) the guide will show past guide too and that messed up the whole EPG because the program detect it current tv show...

It's the guide problem from transvision but i want to know if you can do workaround about it

**Comment by Pancronos** [comment]
i do not see any problem, eventually use the forum. Thanks
