### ISSUE TITLE
pl.canalplus.com.E.ini

### ISSUE THREAD

**Issue by BlackGlassSkin** [SilentButeo2/webgrabplus-siteinipack#446]
works one in 7 propobly 80% no shows in indexpage!

(   1/7   ) PL.CANALPLUS.COM.E -- chan. (xmltv_id=HGTV Home & Garden [23]) -- mode Incremental
iiiii
no shows in indexpage!

**Comment by Pancronos** [comment]
for hgtv use id 329, new version on line
