### ISSUE TITLE
zita.be (Belgium)

### ISSUE THREAD

**Issue by Pancronos** [SilentButeo2/webgrabplus-siteinipack#45]
Site.ini pack goes in error:
[Critical] SiteIni syntax exception:
[Critical]       file: siteini.pack/Belgium/zita.be.ini
[Critical]       line: 8
[Critical]    message: 
[Critical] Multiple identical @Revisionision 2 defined

in site ini:
* @Revision 2 - [09/09/2016] Blackbear199
*   Site changes
* @Revision 2 - [11/12/2012] Willy de Wilde
*   Site changes

**Comment by SilentButeo2** [comment]
Fixed
