### ISSUE TITLE
cinemagia.ro.ini encrypted

### ISSUE THREAD

**Issue by dorinilut** [SilentButeo2/webgrabplus-siteinipack#453]
Hello,

Would it be possible to check cinemagia.ro.ini from the Romanian provider folder. Seems to be encrypted.

Thank you,
Dorin

**Comment by Pancronos** [comment]
Sorry but it is like that. If you do not need elements you can remove with post process.

**Comment by dorinilut** [comment]
> Sorry but it is like that. If you do not need elements you can remove with post process.

I totally understand, and after proper reading I could make it work. My only worry was that the show names for movies would not be in English, but this is working as expected. Sorry for opening something before proper reading.
