### ISSUE TITLE
regression? teleguide.info.ini gives an empty channel list

### ISSUE THREAD

**Issue by bam80** [SilentButeo2/webgrabplus-siteinipack#454]
I get empty channels list with only one entry:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<site generator-info-name="WebGrab+Plus/w MDB &amp; REX Postprocess -- version V2.1.11.0 -- Jan van Straaten" site="teleguide.info">
  <channels>
    <channel update="i" site="teleguide.info" site_id="" xmltv_id="">
    </channel>
  </channels>
</site>
```

It happens until I remove '[alloc](https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/2f4d964b402a8bc6a08b7d733e8203b047afb668/siteini.pack/Russia/teleguide.info.ini#L102)' arguments altogether. Then it starts work OK and gives full channel list.

My program is version V2.1.11.0, Linux.

Please, help.

**Comment by bam80** [comment]
The problem with 'alloc' was confirmed by WG+ author and will be fixed in the next beta.

**Comment by Pancronos** [comment]
Fixed with new version
