### ISSUE TITLE
Unable to update tvpassport channels.xml

### ISSUE THREAD

**Issue by ian10951** [SilentButeo2/webgrabplus-siteinipack#457]
A number of channels have changed names such as Space becoming CTV Sci-Fi so a new channel.xml is needed, but generating one fails.

[ Info ] ( 1/1 ) TVPASSPORT.COM -- chan. (xmltv_id=dummy) -- mode Incremental
[Error ] Unable to update channel dummy
[Critical] Generic syntax exception:
[Critical] message:
[Error ] no index page data received from dummy
[Error ] unable to update channel, try again later
[ Info ] Existing guide data restored!
[ Debug ]
[ Debug ] 0 shows in 1 channels
[ Debug ] 0 updated shows
[ Debug ] 0 new shows added

**Comment by Pancronos** [comment]
you first to generate providers, then channels example:
* <channel update="i" site="tvpassport.com" site_id="10001" xmltv_id="dummy">dummy</channel>
after from channel list generate channels:
    <channel update="i" site="tvpassport.com" site_id="36212D?lineupname=DirecTV+-+New+York%2C+NY+" xmltv_id="DirecTV - New York, NY">DirecTV - New York, NY</channel>

**Comment by ian10951** [comment]
Ok thanks. I will close.
