### ISSUE TITLE
Directv ini is causing Webgrab to close and download no other EPG Data

### ISSUE THREAD

**Issue by ian10951** [SilentButeo2/webgrabplus-siteinipack#459]
Just noticed that for the last 3 days I've not been getting any updated EPG and after checking the log its the Directv ini thats causing this issue.

Group (0) :
update requested for - 238 - out of - 238 - channels for 7 day(s)
(   1/238 ) DIRECTV.COM -- chan. (xmltv_id=BBC America HD (BBCAHD)) -- mode Force
i
error downloading page: The request timed out (20sec)
Retry 1 of 4 times
error downloading page: The request timed out (40sec)
Retry 2 of 4 times
error downloading page: The request timed out (60sec)
Retry 3 of 4 times
error downloading page: The request timed out (80sec)
Retry 4 of 4 times
Job finished at 23/12/2019 13:27:48 done in 3m 23s

Index was outside the bounds of the array.

  at (wrapper stelemref) System.Object.virt_stelemref_sealed_class(intptr,object)
  at WGconsole.Q.UrlBuilder (System.String 0, WGconsole.W 1, System.Int32 2, System.Int32 3, System.Boolean 4, WGconsole.K 5) [0x00733] in <82fae152af5c4c379c1328bc94ed3f01>:0
  at WGconsole.G.1 (System.String[] 0) [0x00a1e] in <82fae152af5c4c379c1328bc94ed3f01>:0
Unhandled Exception
For detailed info, see log file /root/.wg++/./WebGrab++.log.txt
Execution stopped

**Comment by Pancronos** [comment]
Please use forum

**Comment by ian10951** [comment]
Why its the ini that's knackered, what use is discussing a knackered ini that needs a new url.

Anyway Doglover has fixed it on his Git.
