### ISSUE TITLE
Delete dw.de from Networks

### ISSUE THREAD

**Issue by Pancronos** [SilentButeo2/webgrabplus-siteinipack#46]
Please delete from site ini pack dw.de as it causes error:
Multiple siteini's found, with @Revision 1
>  (@Revision 1)siteini.pack/Germany/dw.de.ini
>  (@Revision 1)siteini.pack/Networks/dw.de.ini

**Comment by Pancronos** [comment]
this ini are exactly the same, as myself and I guess lots of other users, get this error using the dw.de site ini.Again is it possible to leave in Germany folder only ?

**Comment by SilentButeo2** [comment]
Done
