### ISSUE TITLE
Added LN24 Channel to yelotv.be.channels.xml

### ISSUE THREAD

**Issue by mikhoul** [SilentButeo2/webgrabplus-siteinipack#460]
I've added the new channel "LN24" to yelotv.be.channels.xml

So you just have to ad this line:  `<channel update="i" site="yelotv.be" site_id="933" xmltv_id="LN24">VLN24</channel>`  to enable the grabbing of the new channel in the yelotv.be.channels.xml file.

Regards :octocat:

**Comment by Pancronos** [comment]
Done, you can also push your channel list thru github
