### ISSUE TITLE
Canalsat not working

### ISSUE THREAD

**Issue by lxsjvln** [SilentButeo2/webgrabplus-siteinipack#463]
The canalsat website from France, not working anymore !

**Comment by mikhoul** [comment]
**Same here:** The site.ini: try tp pull Index from `http://guide.mycanal.fr/library/Pelican/Ajax/Adapter/Jquery/public/?route=Layout_Mycanal_Guide_GrilleTvCorps/grille&&values ` but now it redirect to `https://www.canalplus.com/programme-tv/`

**Comment by Pancronos** [comment]
new ini
