### ISSUE TITLE
Update siteinipack

### ISSUE THREAD

**Issue by abdullasharapov** [SilentButeo2/webgrabplus-siteinipack#467]
Hi! How can i update tv.mail and tv.yandex packs? Both packs are missing many channels. Now i do it manualy. The first one is easier, I find the missing channel on the site, in the link to this channel I find its id and, following the example from tv.mail.ru.channels.xml, add the necessary channels. But with tv.yandex I don’t know how to manually add. Please give instructions or update the lists

**Comment by Pancronos** [comment]
use update c or the old method. More info here : http://www.webgrabplus.com/documentation/configuration/sitechannelsxml
