### ISSUE TITLE
zap2it custom channel/provider

### ISSUE THREAD

**Issue by bizzzkid** [SilentButeo2/webgrabplus-siteinipack#470]
i tried creting my own zap2it channel list but i kept getting a blank xml file. well, not exactly blank but I got this:
`<?xml version="1.0" encoding="UTF-8"?>
<site generator-info-name="WebGrab+Plus/w MDB &amp; REX Postprocess -- version V2.1.11.0 -- Jan van Straaten" site="zap2it.com">
  <channels>
    <channel update="i" site="zap2it.com" site_id="" xmltv_id="">
    </channel>
  </channels>
</site>`

Even on the part where its suppose to create a provider list, it has the same result.
I followed the instructions, step-by-step, I even tried using the exact code that's already in the ini file (`<channel update="i" site="zap2it.com" site_id="zipcode=10001&amp;setMyPreference=false&amp;lineupId=DISH501:-" xmltv_id="DISH New York (New York)">DISH New York (New York)</channel>`) with also the same result so I guess something else has to be chanegd wit the ini file.

Here's the latest log.txt:
`[        ] 
[        ]            WebGrab+Plus/w MDB & REX Postprocess -- version V2.1.11.0            
[        ] 
[        ]                                 Jan van Straaten                                
[        ]                              Francis De Paemeleere                              
[        ] 
[        ]             thanks to Paul Weterings and all the contributing users             
[        ] --------------------------------------------------------------------------------
[        ] 
[        ] Job started at 19/03/2020 01:52:34
[  Debug ] 
[  Debug ] Running  on: Microsoft Windows NT 6.2.9200.0
[  Debug ] Environment: 4.0.30319.42000
[  Debug ] 
[  Debug ] Loading timezone data
[  Debug ] Embedded timezones source: timezone.timezonesdata.txt
[  Debug ] Reading config file: C:\Users\Ona\AppData\Local\WebGrab+Plus\WebGrab++.config.xml
[  Debug ] 
[  Info  ] found: C:\Users\Ona\AppData\Local\WebGrab+Plus\siteini.pack\Networks\zap2it.com.ini -- Revision 02
[Warning ] 
[Warning ] !! SiteIni zap2it.com.ini in channelfile creation mode !!!
[Warning ] 
[  Debug ] xmltv input file - C:\Users\Public\Shared Kodi Items\guide.xml - found
[  Debug ] 0 superfluous shows removed
[  Info  ] Found existing channel (xmltv_id=DISH New York (New York)) in the config file
[  Info  ] 
[  Info  ] 
[  Info  ]       i=index  .=same  c=change  g=gab  r=replace  n=new
[  Info  ] 
[  Info  ] 
[  Info  ] Group (0) :
[  Info  ] update requested for - 1 - out of - 1 - channels for 1 day(s)
[  Debug ] 
[  Info  ] (   1/1   ) ZAP2IT.COM -- chan. (xmltv_id=DISH New York (New York)) -- mode Force
[Error   ] no shows in indexpage!
[  Info  ] 
[  Debug ] 
[  Debug ] 0 shows in 1 channels
[  Debug ] 0 updated shows
[  Debug ] 0 new shows added
[  Info  ] 
[  Info  ] 
[        ] Job finished at 19/03/2020 01:52:37 done in 2s
[  Debug ] statistics upload error: The remote server returned an error: (404) Not Found.
`

Please help and thanks!

**Comment by Pancronos** [comment]
please use forum
