### ISSUE TITLE
tv.nu.ini many descriptions are the same

### ISSUE THREAD

**Issue by hsvi-dk** [SilentButeo2/webgrabplus-siteinipack#480]
Hi,
I have only tried latest version of tv.nu.ini
Description field are identical for many entries in the guide and many others are wrong,
Titles are working but its the descriptions that does not match.
Please fix it.

Please consider isSeries=true/false isMovie=true/false and include this in the officially release as a category if true
http://www.webgrabplus.com/content/tvnuini-add-movie-genre-if-ismovie-eq-true

Thanks

**Comment by Pancronos** [comment]
fixed
