### ISSUE TITLE
update tv.mail.ru part 2

### ISSUE THREAD

**Issue by barzog** [SilentButeo2/webgrabplus-siteinipack#483]
Further fixes (from #472).
Pls update.

[tv.mail.ru.ini.txt](https://github.com/SilentButeo2/webgrabplus-siteinipack/files/5129636/tv.mail.ru.ini.txt)

**Comment by Pancronos** [comment]
please use push siteini to git so we can see the changes

**Comment by Pancronos** [comment]
updated
