### ISSUE TITLE
tet.lv needs fixing

### ISSUE THREAD

**Issue by Theitfixer85** [SilentButeo2/webgrabplus-siteinipack#489]
tet.lv needs fixing - gives the following error

Unable to update channel TV3 Sport HD
[Critical] Generic syntax exception:
[Critical]    message: 
[Error   ] no index page data received from TV3 Sport HD

**Comment by Pancronos** [comment]
Works fine here
[guide.txt](https://github.com/SilentButeo2/webgrabplus-siteinipack/files/5744698/guide.txt)
Also for this type of issue post in http://webgrabplus.com/forum
