### ISSUE TITLE
tv.lv.ini needs fixing

### ISSUE THREAD

**Issue by Theitfixer85** [SilentButeo2/webgrabplus-siteinipack#490]
tv.lv.ini needs fixing

If you grab 1 day it may work but if you grab multiple days eg say at least 4 days you will most likely run in to the following error.

[Error ] Unable to update channel VIASAT Sport East
[Critical] Generic syntax exception:
[Critical] message:
[Error ] Current culture: en-GB
[Error ] time parsing error : String was not recognized as a valid DateTime.
[Error ] nextstarttime time scrubbed :
[Error ] computer date/time format: 29/11/2020 11:47:44
[ Info ] Existing guide data restored!

I get this error on a lot of channels

Also get this error on some channels eg National Geographic Channel HD
skipped show without a title at

Stopped working about 2 weeks ago

**Comment by Pancronos** [comment]
it looks like a site problem, no epg for some channels. Please for this problem use the forum. Thanks
