### ISSUE TITLE
yelotv.be changes

### ISSUE THREAD

**Issue by kyl416** [SilentButeo2/webgrabplus-siteinipack#494]
yelotv.be (Yelo Play) changed how you fetch details for individual shows. At quick glance it looks like they no longer use the eventid, and instead use the crid value for the show pages.

There might have been some other changes, so you might want to look on how the show pages from their tv-guide work:
https://www.yeloplay.be/tv-guide

**Comment by Laibalion** [comment]
I've just created a PR that should fix this in PR #495

**Comment by Pancronos** [comment]
see new
