### ISSUE TITLE
vivacom.bg

### ISSUE THREAD

**Issue by Chris230291** [SilentButeo2/webgrabplus-siteinipack#498]
Hello. Is it possible to pull episode numbers for this site?
Seems to be included in the descriptions...
`  <programme start="20210205000500 +0200" stop="20210205003000 +0200" channel="Discovery Science HD">
    <title lang="bg">Как се прави</title>
    <desc lang="bg">еп. 11, сез. 25. Комплекти за бистро, преса за печатане. Още продукти за ежедневна употреба под микроскопа! Вижте как се правят бамбукови керамични лампи и валяци за асфалт.(n)</desc>
  </programme>`

Is there any way to get original title names?

**Comment by Pancronos** [comment]
updated, please next time use forum for this type of issue
