### ISSUE TITLE
DE: Sky Crime HD missing/not working?

### ISSUE THREAD

**Issue by forenta** [SilentButeo2/webgrabplus-siteinipack#533]
I've tried both ways, but somehow I haven't been able to grab any content yet:

[Source](https://www.sky.de/static/img/senderlogos_dark/855_sky_logo_crime-hd_tvguide.png) [Schedule](https://www.sky.de/tvguide/sky-crime-hd-c855)
`<channel update="i" site="sky.de.E" site_id="855_sky_logo_crime-hd_tvguide" xmltv_id="Sky Crime HD">Sky Crime HD</channel>`

[Source/Schedule](https://info.sky.de/inhalt/de/programminfo_kanaluebersicht_373_skycrimehd.jsp)
`<channel update="i" site="sky.de" site_id="373" xmltv_id="Sky Crime HD">Sky Crime HD</channel>`

**Comment by Pancronos** [comment]
hi, tested sky.de.E and works fine.  Sky.de site is very slow and you need high retry-timeout ( i have 180)
Please use forum for this type of issues.
[WebGrab++.log.txt](https://github.com/SilentButeo2/webgrabplus-siteinipack/files/8005527/WebGrab%2B%2B.log.txt)
[guide1.txt](https://github.com/SilentButeo2/webgrabplus-siteinipack/files/8005531/guide1.txt)

**Comment by Pancronos** [comment]
Saw some channels in main page have no schedule, so i updated siteini
