### ISSUE TITLE
tv.blue.ch: MySports 7-9 D missing

### ISSUE THREAD

**Issue by forenta** [SilentButeo2/webgrabplus-siteinipack#534]
Should be listed after MySports 6 D: [tv.blue.ch.channels.xml#L265](https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/siteini.pack/Switzerland/tv.blue.ch.channels.xml#L265)

```
<channel update="i" site="tv.blue.ch" site_id="1548##44612629-a1d2-f300-7048-501a95af27fd" xmltv_id="MySports 6 D">MySports 6 D</channel>
<channel update="i" site="tv.blue.ch" site_id="1549##XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" xmltv_id="MySports 7 D">MySports 7 D</channel>
<channel update="i" site="tv.blue.ch" site_id="1550##XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" xmltv_id="MySports 8 D">MySports 8 D</channel>
<channel update="i" site="tv.blue.ch" site_id="1551##XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" xmltv_id="MySports 9 D">MySports 9 D</channel>
```

I don't know how to find out the ID in case on 'blue' so it'll be nice if someone could add the missing channels:

https://services.sg101.prd.sctv.ch/content/images/tv/channel/1549_image_7_w90.webp
https://services.sg101.prd.sctv.ch/content/images/tv/channel/1550_image_7_w90.webp
https://services.sg101.prd.sctv.ch/content/images/tv/channel/1551_image_7_w90.webp

blue TV guide: [tv.blue.ch/tv-guide](https://tv.blue.ch/tv-guide
)

**Comment by Pancronos** [comment]
hi updated chan list
