### ISSUE TITLE
add_logo processing bug

### ISSUE THREAD

**Issue by nc88keyz** [SilentButeo2/webgrabplus-siteinipack#544]
Running the plugin will fail every time on these xmltv_id s. 

here is the logos-ini UTF-8 file

Wilmington, NC WWAY ABC 3 A3 HD , http://myurl/icons/ABC.png
Wilmington, NC WWAYDT3 CW 4 A3 SD , http://myurl/icons/icons/CW.png 
Wilmington, NC WWAYDT2 CBS 5 A3 HD , http://myurl/icons/CBS.png
Wilmington, NC WECT NBC 6 A3 HD , http://myurl/icons/NCB.png
Wilmington, NC WSFX FOX 26 A3 HD , http://myurl/icons/FOX.png
Wilmington, NC WUNJ PBS 39 A3 HD , http://myurl/icons/PBS.png

below is the channel tag from the directv.com.channels.xml that matches: 

<channel update="i" site="directv.com" site_id="3#_#2091" xmltv_id="Wilmington, NC WWAY ABC 3 A3 HD">Wilmington, NC WWAY ABC 3 A3 HD</channel>
    <channel update="i" site="directv.com" site_id="4#_#4137" xmltv_id="Wilmington, NC WWAYDT3 CW 4 A3 SD">Wilmington, NC WWAYDT3 CW 4 A3 SD</channel>
    <channel update="i" site="directv.com" site_id="5#_#4134" xmltv_id="Wilmington, NC WWAYDT2 CBS 5 A3 HD">Wilmington, NC WWAYDT2 CBS 5 A3 HD</channel>
    <channel update="i" site="directv.com" site_id="6#_#2092" xmltv_id="Wilmington, NC WECT NBC 6 A3 HD">Wilmington, NC WECT NBC 6 A3 HD</channel>
    <channel update="i" site="directv.com" site_id="10#_#2093" xmltv_id="Wilmington, NC WILM IND 10 A3 SD">Wilmington, NC WILM IND 10 A3 SD</channel>
    <channel update="i" site="directv.com" site_id="26#_#2094" xmltv_id="Wilmington, NC WSFX FOX 26 A3 HD">Wilmington, NC WSFX FOX 26 A3 HD</channel>
    <channel update="i" site="directv.com" site_id="39#_#4312" xmltv_id="Wilmington, NC WUNJ PBS 39 A3 HD">Wilmington, NC WUNJ PBS 39 A3 HD</channel>

all the others work. just not the locals, is there something in the plugin that will not read a comma between the city and state. If I shorten it but that will break the guide xml a it wont see any data in the guide with the wrong channel id., but it will process all the url changes to my logo files.

I don't have any more ideas how to get this to work as it just skips all of these and then proceeds to process the other logos just fine. 
This is replicated on 3.2x and the latest versions WebGrabPlus as well. The plugin seems to be the same version. 

Using 1.03 version of the postprocess plugin.

Maybe something could be patched up for this.

**Comment by nc88keyz** [comment]
It looks like this is complete. Is there anyway to get the add_logo.exe file without building from source at this point. My head is already spinning from all of this after joining webgrabplus. The exe from the bin/release folder did not work. I guess it hasnt been posted yet?

**Comment by WGMaker** [comment]
Hi .. its there .. https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/postprocess_plugins/add-logo/add_logo_exe.zip, unzip and copy to your config folder .. Jan

**Comment by nc88keyz** [comment]
This is my command from terminal; Just trying to get it working first before scripting it. 

mono add_logo.exe /in=/volume1/docker/webgrabplus/data/guide.xml /out=/volume1/web/epg/directv.me.xml /logos=l                           ogos.ini

Output: ( Notice the version number) 1.03 This is the one i downloaded from the link you provided and i checked version on both. Also checked permissions. and made it executable. Its working for everything but the locals.  Did you change the version number: If so can you please double check the one you packed, If not is this a mono issue that will not operate correctly with the revised exe allowing for the comma in the channel-id?  I don't know what else to try except to debug on windows now if there is nothing wrong with the add_logo.exe. Thank you for your support in troubleshooting this.  In my .logos.ini file i have a space-comma-space and comma-space between the channel id and the url.  Either way the locals are ignored from the add_logo output lines.  

Output from command above: 
Add or change channel logos in xmltv files
Version 1.0.3 Jan van Straaten , November 2021

'ION Television East HD'   logo replaced by 'http://url.com/icons/ION.png'
'FX Movie Channel HD'      logo replaced by 'http://url.com/icons/FXMC.png'
'GAC Family HD'            logo replaced by 'http://url.com/icons/GAC.png'
'AccuWeather HD'           logo replaced by 'http://url.com/icons/ACCU.png'

logos.ini contents: 

Wilmington, NC WWAY ABC 3 A3 HD , http://url.com/icons/icons/ABC.png
Wilmington, NC WWAYDT3 CW 4 A3 SD , http://url.com/icons/icons/CW.png 
Wilmington, NC WWAYDT2 CBS 5 A3 HD , http://url.com/icons/icons/CBS.png
Wilmington, NC WECT NBC 6 A3 HD , http://url.com/icons/NBC2.png
Wilmington, NC WILM IND 10 A3 SD , http://url.com/icons/MISSING.png
Wilmington, NC WSFX FOX 26 A3 HD , http://url.com/icons/icons/FOX.png
Wilmington, NC WUNJ PBS 39 A3 HD , http://url.com/icons/PBS.png
ION Television East HD , http://url.com/icons/ION.png
FX Movie Channel HD , http://url.com/icons/FXMC.png
GAC Family HD , http://url.com/icons/GAC.png
AccuWeather HD , http://url.com/icons/ACCU.png

**Comment by nc88keyz** [comment]
An update and perhaps a bug discovery. 

I wasn't aware you had to close the logos.ini UTF-8 txt file with a * at the end of your entries.   As soon as i did this the command works from terminal. Before I was getting a system min 32 error so I considered the url was too long. 

for example.   http://username.direct.quickconnect.to/icons/abc-us-network.png

So i changed the length and played with it still no success. 

Eventually i looked at the file and decided to add a * on the next line below the lines for change. 

Is this an oversight or an issue with length of url. there are some pretty long dyndns redirect urls out there from what I gather, but that did not seem to change the error.: Here is the error received exactly:  I had to remove the * to get that to echo back again on the command line. 

Sample change line: 
Wilmington, NC WWAY ABC 3 A3 HD , http://username.direct.quickconnect.to/icons/abc2.png



``Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at add_logo.Program.Main(String[] args)

Adding the * results in 11 logos changed and no error output ( Windows)
I have not tryed the docker yet, but i suspect that is the solution as the error I believe was identical.
I assume you did not change the version on add_logo.exe as well to 1.04 vs. 1.03 for debug testing at this point. 

Output successful looks like below: 
PS C:\Users\nc88keyz\AppData\Local\WebGrab+Plus> .\add_logo.exe /in=guide.xml /out=directvme.xml /logos=logos.ini
Add or change channel logos in xmltv files
Version 1.0.3 Jan van Straaten , November 2021

'Wilmington, NC WWAY ABC..'logo replaced by 'http://username.direct.quickconnect.to/icons/abc2.png'
'Wilmington, NC WWAYDT3 ..'logo replaced by 'http://username.direct.quickconnect.to/icons/cw2.png'
'Wilmington, NC WWAYDT2 ..'logo replaced by 'http://username.direct.quickconnect.to/icons/cbs2.png'
'Wilmington, NC WECT NBC..'logo replaced by 'http://username.direct.quickconnect.to/icons/nbc2.png'
'Wilmington, NC WILM IND..'logo replaced by 'http://username.direct.quickconnect.to/me2.png'
'Wilmington, NC WSFX FOX..'logo replaced by 'http://username.direct.quickconnect.to/icons/fox2.png'
'Wilmington, NC WUNJ PBS..'logo replaced by 'http://username.direct.quickconnect.to/icons/pbs2.png'


Results saved in C:\Users\username\AppData\Local\WebGrab+Plus\directvme.xml
.. done ..

I feel like an idiot if the * was needed all along, but i swear i read the documentation and samples and determined there was nothing needed there. If it was , my apologies for wasting your valuable time.

**Comment by WGMaker** [comment]
Hi, yes that is obvious, it sees the first comma as separator between the channel id and the logo value .. pls send me the xmltv file (or at least a part that contain these channels. I will fix it as soon as I have some time.
regards    Jan

From: nc88keyz ***@***.***>
Sent: 23 August 2022 20:00
To: SilentButeo2/webgrabplus-siteinipack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SilentButeo2/webgrabplus-siteinipack] add_logo processing bug (Issue #544)


Running the plugin will fail every time on these xmltv_id s.

here is the logos-ini UTF-8 file

Wilmington, NC WWAY ABC 3 A3 HD , http://myurl/icons/ABC.png
Wilmington, NC WWAYDT3 CW 4 A3 SD , http://myurl/icons/icons/CW.png
Wilmington, NC WWAYDT2 CBS 5 A3 HD , http://myurl/icons/CBS.png
Wilmington, NC WECT NBC 6 A3 HD , http://myurl/icons/NCB.png
Wilmington, NC WSFX FOX 26 A3 HD , http://myurl/icons/FOX.png
Wilmington, NC WUNJ PBS 39 A3 HD , http://myurl/icons/PBS.png

below is the channel tag from the directv.com.channels.xml that matches:

Wilmington, NC WWAY ABC 3 A3 HD
Wilmington, NC WWAYDT3 CW 4 A3 SD
Wilmington, NC WWAYDT2 CBS 5 A3 HD
Wilmington, NC WECT NBC 6 A3 HD
Wilmington, NC WILM IND 10 A3 SD
Wilmington, NC WSFX FOX 26 A3 HD
Wilmington, NC WUNJ PBS 39 A3 HD

all the others work. just not the locals, is there something in the plugin that will not read a comma between the city and state. If I shorten it but that will break the guide xml a it wont see any data in the guide with the wrong channel id., but it will process all the url changes to my logo files.

I don't have any more ideas how to get this to work as it just skips all of these and then proceeds to process the other logos just fine.
This is replicated on 3.2x and the latest versions WebGrabPlus as well. The plugin seems to be the same version.

Using 1.03 version of the postprocess plugin.

Maybe something could be patched up for this.

-
