### ISSUE TITLE
skynetdth.com

### ISSUE THREAD

**Issue by unlocKing** [SilentButeo2/webgrabplus-siteinipack#55]
.ini needs updating..

No longer grabbing data or creating channel list.

Thanks.

**Comment by Netuddki** [comment]
I fixed it, but I can't fully test it because the site has no data beyond 26. February 2017, so actually you can't grab anything, even if the ini is fixed.

**Comment by unlocKing** [comment]
Sport channels are showing on this page with data:

http://skynetdth.com/index.php/sport-schedule

http://skynetdth.com/index.php/sport-schedule/sport-schedule

Main page does not show sports, weird setup?

**Comment by Netuddki** [comment]
That site is built completely differently. That would need a complete different ini.
Maybe it could be integrated into one ini, but even if possible, it would be very complicated.
There is almost nothing common in the two pages, which could be used as basis for grabbing.

**Comment by unlocKing** [comment]
Maybe they have 2 dif people adding epg data, seems very strange tho.

Seeing that the main page has had no data, maybe it's worthwhile setting this page as a new ini then?

**Comment by Netuddki** [comment]
I will create a separate ini  in a few days and we will see if the guys do want it.

**Comment by unlocKing** [comment]
Cool, appreciate it.

Cheers!

**Comment by Netuddki** [comment]
I think the site is dead.
They had yesterday the last day when they had program for sport.
I was almost finished with the ini, but I still need to figure something out. I will continue, when they update the site.

**Comment by unlocKing** [comment]
Cool, many thanks for keeping an eye on this..

**Comment by unlocKing** [comment]
Data is back on both parts of the site.. shame it's the only place to get epg for these channels.

**Comment by unlocKing** [comment]
Working solution posted by suzi:

http://www.webgrabplus.com/content/sky-net-sports-site-help
