### ISSUE TITLE
Please update dishtv.in.channels.xml

### ISSUE THREAD

**Issue by dheer99** [SilentButeo2/webgrabplus-siteinipack#555]
hi,
could you please update the channel list in dishtv.in.channels.xml.

**Comment by WGMaker** [comment]
You can do that yourself .. use the <update>c</update> mode . Read   WebGrab++.config.documented.xml  http://webgrabplus.com/sites/default/files/downloads/Misc/Documented_Configuration_Files.zip

From: dheer99 ***@***.***>
Sent: 26 June 2023 11:07
To: SilentButeo2/webgrabplus-siteinipack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SilentButeo2/webgrabplus-siteinipack] Please update dishtv.in.channels.xml (Issue #555)


hi,
could you please update the channel list in dishtv.in.channels.xml.

-

**Comment by WGMaker** [comment]
Works perfect here .. the same info is also here http://webgrabplus.com/documentation/configuration/webgrabconfigxml#config_update

**Comment by dheer99** [comment]
sorry to bother you again, if you can update and share please, as I am a bit low with codes.

**Comment by WGMaker** [comment]
What is your wg++ username ? We have no-one with name dheer99 !!

**Comment by dheer99** [comment]
my user id is dheer for webgreb website.

**Comment by dheer99** [comment]
can someone assist

**Comment by WGMaker** [comment]
Hi .. I gave you the instructions and  it's very simple .. just use <update>c</update> with at least one dishtv channel in the channel list. And.. normally we do not do support for non contributing registered uusers
