### ISSUE TITLE
Fox channels

### ISSUE THREAD

**Issue by Thermaldude** [SilentButeo2/webgrabplus-siteinipack#562]
The fox channels in vodafone.xml (Portugal) , fox; fox movies;fox comedy;fox crime change the name to STAR Movies  star comedy star crime and star, possible update? Thks

**Comment by WGMaker** [comment]
http://webgrabplus.com/faq#faq_6858

From: Thermaldude ***@***.***>
Sent: Thursday, February 15, 2024 11:49 AM
To: SilentButeo2/webgrabplus-siteinipack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SilentButeo2/webgrabplus-siteinipack] Fox channels (Issue #562)


The fox channels, fox; fox movies;fox comedy;fox crime change the game to STAR Movies star comedy star crime and star, possible update? Thks

-

**Comment by Pancronos** [comment]
Please use forum
