### ISSUE TITLE
webgrabplus.com can't be proper open

### ISSUE THREAD

**Issue by litalgion** [SilentButeo2/webgrabplus-siteinipack#563]
Hello,

I hope this is the right place to write, I already had try to send e-mails to 

**webgrabpp@gmail.com** and **info@webgrabplus.com** but got no answer so far.

I was trying whole week to access the **http://webgrabplus.com/** and it's not working for me. 

I attached what my browsers shows me. I have try with Opera, Edge and Chrome and it was the same result (see Attachament).

I am a registered user and I am interested to give it a try as a donor.

Can you tell me why I cant acces the site(until Monday I could)? Do you have some sort of **technical problems?** 

Thank you in advance!
![IMG-20240314-WA0000](https://github.com/SilentButeo2/webgrabplus-siteinipack/assets/157634101/610ca882-0272-4c3c-84ec-cb9195f0c07d)

**Comment by moob158** [comment]
me too, what's wrong with the site?

**Comment by litalgion** [comment]
Now works
