### ISSUE TITLE
postprocess_plugins/add-logo/add_logo.py

### ISSUE THREAD

**Issue by Marvicek** [SilentButeo2/webgrabplus-siteinipack#568]
Hello 
I try use this scritp and i get error:

Job (/usr/bin/python3 add_logo.py --xmltv_in=guide.xml --logos=logos.ini --xmltv_out=guide_with_logo.xml) started at 15/09/2024 07:21:24
Traceback (most recent call last):
  File "/home/hts/Programy/EPG/WebGrab++_1/add_logo.py", line 115, in <module>
    main()
  File "/home/hts/Programy/EPG/WebGrab++_1/add_logo.py", line 56, in main
    for xmltv_id_ini, new_icon in content_reader:
        ^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
External program had exit code 1
  Program: /usr/bin/python3 add_logo.py --xmltv_in=guide.xml --logos=logos.ini --xmltv_out=guide_with_logo.xml
  Params : add_logo.py --xmltv_in=guide.xml --logos=logos.ini --xmltv_out=guide_with_logo.xml
Job (/usr/bin/python3 add_logo.py --xmltv_in=guide.xml --logos=logos.ini --xmltv_out=guide_with_logo.xml) finished at 15/09/2024 07:21:24 done in 0s

Is possibly to fix this error? 
Or is mystake on my side?

Thaks Martin

**Comment by Pancronos** [comment]
Please use forum for support
