### ISSUE TITLE
Virgin Media Ireland

### ISSUE THREAD

**Issue by unlocKing** [SilentButeo2/webgrabplus-siteinipack#74]
https://www.virginmediatv.ie/en/tv-guide.html

Can you take a look at creating an ini for this site as it has channels not shown elsewhere.

Thanks.

**Comment by Netuddki** [comment]
That site is generated with Silverlight. I don't think that it's possible.
It seems that they are getting the programming from Horizon.tv anyway.
Horizon has its own ini and channel list that also contains ireland.

**Comment by unlocKing** [comment]
Just took a closer look and you're right about Horizon.

Thanks.
