### ISSUE TITLE
Add channel icon

### ISSUE THREAD

**Issue by superdevil669** [SilentButeo2/webgrabplus-siteinipack#78]
`index_urlchannellogo.modify {set|http://icon.telerama.fr/tele/imedia/images_chaines_tra/Transparent/80x80/'config_site_id'.png}`

**Comment by Netuddki** [comment]
What do you expect?

**Comment by superdevil669** [comment]
https://github.com/superdevil669/webgrabplus-siteinipack/commit/5e2d82a8055a15493997d6cb671dfd0879a3d485

**Comment by SilentButeo2** [comment]
If you have already made a patch, just make a Pull request the next time. Than your change will be added directly into the pack. Just did this for you this time.
Thanks for helping out!
